name: Tman designer UI

on:
  workflow_dispatch:

jobs:
  test:
    name: Tman designer UI
    runs-on: ubuntu-latest

    services:
      selenium:
        image: selenium/standalone-chrome
        options: --shm-size=2gb

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
